##################################################
##################################################
#tutorial R code for the introduction to R course
#section: 1.data management
#institution: University of Oxford
#year: 2020
##################################################
##################################################


#1.0 WELCOME TO R STUDIO
#Please follow the instructions provided during the course and feel free to consult the R cheatsheets.
#The symbol "#" at the beginning of a line indicates a comment instead of an R code.
#Don't hesitate to amend the comments and code to answer the questions and further explore the functionalities of R.

#1.1 HOW TO RUN AN R CODE LINE
#Take few minutes to consult the R-cheatsheet.pdf (in folder tutorial) and explore the R Studio environment.
#To run a code line, left-click anywhere on a line code and press Ctrl+Enter (for MAC: Command+Enter).
#Run each line below and observe the results in the Console (bottom-left window of R studio)
#First, make sure all packages required for the course are installed.
#the following lines install the required packages for the course that are not yet installed on your machine
list.of.packages <- c("stats","corrplot","Hmisc","rgdal","rgeos","stargazer","rticles","rmarkdown","knitr","tidyverse", "gridExtra","ggplot2","GGally","MASS","brinla", "gapminder","gganimate", "gifski", "png")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

#1.2 set your working directory
#check where is the current working directory
getwd()

#set the working directory based on the location where you saved the folder `tutorial`.
#uncomment the line below (remove "#"), amend the location (based on your own folder) and run it:
setwd("E:/Dropbox/projectRMathDphil/2020/tutorial")


#check that the new working directory is correcly defined
getwd()

#By running the command setwd(), you have set your working directory. Furthermore, you have printed its path
#with the command getwd(). 

#2. FIRST EXERCISE 

#To import the data for our exercise, run the following line, read the comments, and answer the questions. 
df <- read.csv("data/mtcars.csv")

#2.1 INFORMATION ON THE DATA
#The dataset `mtcars` was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and
#10 aspects of automobile design and performance for 32 automobiles (1973 to 1974 models).
#more info type `??mtcars` in your Console (bottom-left window in R studio) en press `Enter`.

#2.2 SOME INFORMATION ON R OBJECTS
#By applying the command read.csv on the argument "mtcars.csv", you have imported a csv file named "mtcars.csv",
#which is located in your folder .../tutorial/data. The import process has generated a dataframe called "df" (see Environment tab in top-right window).
#Note the direction of the arrow "<-", which signifies that the imported file `mtcars.csv` is assigned to the object `df`.
#Further information on dataframe objects: read the dataframe info box on p.2 of the r-cheatsheet.pdf (in folder `tutorial`)

#2.3 QUESTIONS
# a) What is the main role of `R Studio`?
# b) What represent the columns and rows of the object `df`?

#You can generate summary statistics with the command "summary". Run the following line and answer the question
summary(df)

# 3. What has been generated by R? Try to interpret the result

#One can subset the data with the command `[...]`. Run the following line:
hp<-df[,5]

df10obs<-df[1:10,1:10]

# a) What is the role of `[]` and how the position of `,` within `[]`` is used to subset data ?

#We often deal with large datasets. 
# b) How to view only the first lines of a dataframe? Run the following line:
head(df,3)

# c) What is the output generated by the command `head` on the object `df`? 
# d) Extract the variable `mpg` from the dataframe `df` and provide a summary of the generated subset.

# 4. Generate new objects
a <- c(1,2,5.3,6,-2,4) 
b <- c("one","two","three") # character vector
c <- c(TRUE,TRUE,TRUE,FALSE,TRUE,FALSE) #logical vector
y <- matrix(1:20, nrow=5,ncol=4)# matrix
w <- list(name="Fred", mynumbers=a, mymatrix=y, age=5.3)

# a) What are the differences between the following objects? Use the command `class` to determine the nature of the object.
class(a)
class(b)
class(c)
class(y)
class(df)
class(w)

#5. Identify row and columns of a matrix using subscripts
y[,4] # 4th column of matrix
y[3,] # 3rd row of matrix 
y[2:4,1:3] # rows 2,3,4 of columns 1,2,3

#6. Get elements of a list. See the line below. 
#a) What does the command [[2]] do?
w[[2]]

vecsel<-c("mpg","cyl")
dfsub<-df[vecsel]
names(dfsub)<-c("a","b")

#7. Explore the following useful basic functions in R. 
#Note that we use `df` as an example of an object but you can replace it with another object created above.

length(df) # number of elements or components
str(df)    # structure of an object 
class(df)  # class or type of an object
names(df)  # names

c(12,24,"blue")        # combine objects into a vector
cbind(13, 15,"red",13) # combine objects as columns
dfall<-rbind(df, df) # combine objects as rows 

df     # prints the object
ls()   # list current objects
rm(hp,dfall) # delete an object

myvec <- c(12,24,"blue") # <- assign to a new object

##################################################
##################################################
#end of section 1.data management
##################################################
##################################################

